apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: postgis
  name: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgis    
  strategy:
    type: Recreate
  template:
    metadata:  
      labels:
        name: postgis
    spec:
      containers:
        - name: db4geonetwork
          image: mdillon/postgis:9.6
          env:
            - name: POSTGRES_PASSWORD
              value: geonetwork
            - name: POSTGRES_USER
              value: geonetwork
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgis/data
              name: repositorie-data
      volumes:
        - name: repositorie-data
          persistentVolumeClaim:
            claimName: repositorie-data-claim
status: {}
