apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repositorie-data-claim-felipe
  namespace: felipe
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
