apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repositorie-data-claim-gabriel
  namespace: gabriel
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
