apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: analysis
  name: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: analysis     
  strategy:
    type: Recreate
  template:
    metadata:  
      labels:
        name: analysis
    spec:
      containers:
      - command:
        - /usr/local/bin/start_terrama2_service.sh
        - ANALYSIS
        - "6544"
        image: terrama2/terrama2:4.0.11
        name: analysis
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /data
          name: repositorie-data
        - mountPath: /shared-data
          name: repositorie-data
      restartPolicy: Always
      volumes:
        - name: repositorie-data
          persistentVolumeClaim:
            claimName: repositorie-data-claim
status: {}
