apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: webmonitor
  name: webmonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webmonitor  
  strategy:
    type: Recreate
  template:
    metadata:  
      labels:
        name: webmonitor
    spec:
      containers:
      - image: terrama2/terrama2-webmonitor:4.0.11
        name: webmonitor
        ports:
        - containerPort: 36001
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: repositorie-data
        - mountPath: /shared-data
          name: repositorie-data
        - mountPath: /root/
          name: pgpass-config
        - mountPath: /opt/terrama2/4.0.11/webmonitor/config/instances/
          name: webmonitor-config
      restartPolicy: Always
      volumes:
        - name: repositorie-data
          persistentVolumeClaim:
            claimName: repositorie-data-claim
        - name: pgpass-config
          configMap:
            name: pgpass-config
        - name: webmonitor-config
          configMap:
              name: webmonitor-config
status: {}
